version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd backend
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp package.json build/package.json
      - cd build
      - npm i --production

artifacts:
  files:
    - "**/*"
  base-directory: backend/build
  name: getbots-backend-$(AWS_REGION)-$(date +%Y-%m-%d)
